### ISSUE TITLE
How can I add other lang?

### ISSUE THREAD

**Issue by Saruqui** [jakubroztocil/rrule#178]
How can I add other languages to use the function .toText() ? I'm not sure what's the best way to do it.

Thanks in advance

**Comment by kkostov** [comment]
I believe `toText()` takes some extra parameters which can include a custom language definition object.
You can lookup the default `ENGLISH` object in the source [here](https://github.com/jakubroztocil/rrule/blob/master/lib/nlp.js) and I also found an older comment making a note of the usage [here](https://github.com/jakubroztocil/rrule/issues/13#issuecomment-16511597) e.g. `rule.toText(null, gettext, yourlanguageobject)`

**Comment by dehlen** [comment]
Hi i am also interested in supporting a different language, however as already stated in #13 this won't work with the current API because grammar differs for other languages. Any chances we might see a reworked API in the future to better support i18n ?

Just came across this issue because i am about to implement something like this work a project i am working on. I might get some time to have a look by myself but if someone already started something like this I'd love to hear about that :)

**Comment by Wakirin** [comment]
https://github.com/rlanvin/php-rrule/blob/master/src/i18n/en.php
I think that is implementation better, but need adaptive it

**Comment by espen** [comment]
Closed in favour of #13
