### ISSUE TITLE
DST not applied with tzid

### ISSUE THREAD

**Issue by KrisBraun** [jakubroztocil/rrule#294]
When generating a sequence of instances using a tzid with DST, the resulting UTC times are consistent throughout the year. Shouldn't they be offset by one hour in UTC during DST?

On node v8.11.4 with rrule 2.5.6 and luxon 1.4.4 on a machine in EDT:
```
const rrule = require('rrule')
console.log(
    new rrule.RRule({
        freq: rrule.RRule.MONTHLY,
        dtstart: (Date.UTC(2018, 0, 1, 10, 30)),
        until: (Date.UTC(2018, 11, 31)),
        tzid: 'America/New_York',
    }).all()
)
``` 
Output:
```
[ 2018-01-01T10:30:00.000Z,
  2018-02-01T10:30:00.000Z,
  2018-03-01T10:30:00.000Z,
  2018-04-01T10:30:00.000Z,
  2018-05-01T10:30:00.000Z,
  2018-06-01T10:30:00.000Z,
  2018-07-01T10:30:00.000Z,
  2018-08-01T10:30:00.000Z,
  2018-09-01T10:30:00.000Z,
  2018-10-01T10:30:00.000Z,
  2018-11-01T10:30:00.000Z,
  2018-12-01T10:30:00.000Z ]
```

**Comment by KrisBraun** [comment]
I found I was able to solve this for icals with `VTIMEZONE` sections by using `ical.js` like this (no tzid support from luxon required):

```
const convertToUtc = (jsDate, icalTimezone) => {
  const time = ical.Time.fromJSDate(jsDate)
  time.adjust(0, 0, 0, -icalTimezone.utcOffset(time))
  return time.toJSDate()
}

const comp = new ical.Component(ical.parse(data))
const vevent = comp.getFirstSubcomponent('vevent')
const event = new ical.Event(vevent)
const rrule = vevent.getFirstPropertyValue("rrule").toString()
const vtz = comp.getFirstSubcomponent("vtimezone");
const tz = new ical.Timezone(vtz)
const dtstart = event.startDate.toJSDate()
const dates = rrulestr(rrule, { dtstart })
  .between(new Date(), addMonths(new Date(), 1))
  .map(date => convertToUtc(date, tz))
```

**Comment by davidgoli** [comment]
Can I ask, what's your machine's timezone?

**Comment by davidgoli** [comment]
If your local timezone is `America/New_York`, then this looks correct to me. The only misleading portion here is the resulting dates are actually in the requested local time, not UTC, even though they appear as "UTC" (their offset is given as `Z`) instead of with the expected timezone offset of `-0400` or `-0500`.

This is explained in the documentation, though it could perhaps be clearer.

In fact, I'd go so far to say that ical.js' "timezone support" is probably a lie, and it only really "supports" UTC and your current machine's timezone. Working in any other timezone is going to give you incorrect results.

In JavaScript, the interpreter doesn't really know about any timezones other than UTC and your local timezone. In fact, JavaScript can't create dates that intrinsically have arbitrary timezone offsets:

```js
> new Date('2018-12-01T02:30:00.000-05:00').getTimezoneOffset()
480
> new Date('2018-12-01T02:30:00.000-08:00').getTimezoneOffset()
480
> new Date('2018-10-01T02:30:00.000Z').getTimezoneOffset()
420
> new Date()
2018-10-28T21:43:19.919Z
```

Luxon, however, is able to use extended APIs to support every timezone in the world. The only catch is the returned dates always appear as though they were UTC when they are in fact localized with the correct offset applied. If this library returned Luxon `DateTime` objects instead of native `Date`s, the `DateTime`s could have arbitrary offsets applied (and be converted into strings with those offsets). But the best approach we could find with native JS `Date` objects is to return dates without a local timezone applied at all.

Does this clear things up at all?

**Comment by KrisBraun** [comment]
Yes, you corrected my confusion that the returned times are UTC, when they're actually local. So what I need to do is use Luxon with the returned times to convert them to UTC. Thanks!

**Comment by kelvin-thinkbean** [comment]
What about when the local time is in UTC?
