### ISSUE TITLE
DTEND seems to be an invalid property

### ISSUE THREAD

**Issue by imrealashu** [jakubroztocil/rrule#322]
`FREQ=MONTHLY;DTSTART=20181114T110000;DTEND=20191114T140000;INTERVAL=1` this seems to be invalid saying . 
`Error: Unknown RRULE property 'DTEND'`
I checked the ical rules and seems to be present in the ruleset https://www.kanzaki.com/docs/ical/rrule.html

Even I'm using one PHP version which does letting me parse it properly https://github.com/simshaun/recurr

**Comment by davidgoli** [comment]
That's correct, it is a property that's present in the spec, but not supported by this library (currently). The reason is that this library does not support the concept of "duration" which is what `DTEND` represents, and it's not clear how to add support for duration without a major overhaul of the library. See discuss here: https://github.com/rlanvin/php-rrule/issues/4

Note that the rrule properties as you have them are invalid. According to the spec, `DTSTART` and `DTEND` do not appear within the `RRULE:` property string, but at the top level as peers of the `RRULE:`. Supported properties (all of which this library supports):

```
       recur-rule-part = ( "FREQ" "=" freq )
                       / ( "UNTIL" "=" enddate )
                       / ( "COUNT" "=" 1*DIGIT )
                       / ( "INTERVAL" "=" 1*DIGIT )
                       / ( "BYSECOND" "=" byseclist )
                       / ( "BYMINUTE" "=" byminlist )
                       / ( "BYHOUR" "=" byhrlist )
                       / ( "BYDAY" "=" bywdaylist )
                       / ( "BYMONTHDAY" "=" bymodaylist )
                       / ( "BYYEARDAY" "=" byyrdaylist )
                       / ( "BYWEEKNO" "=" bywknolist )
                       / ( "BYMONTH" "=" bymolist )
                       / ( "BYSETPOS" "=" bysplist )
                       / ( "WKST" "=" weekday )
```

**Comment by pantonis** [comment]
This is a must!!!!!!!!!!!!!!!

**Comment by espen** [comment]
@pantonis feel free to send a pull request for this to get it included.

**Comment by pantonis** [comment]
@espen I am not a JavaScript dev. I would create more problems rather than solve. :D If I knew be sure that I would do create a pull request.
