### ISSUE TITLE
Crashes without luxon

### ISSUE THREAD

**Issue by froatsnook** [jakubroztocil/rrule#344]
Luxon is an optional dependency and I'd rather not include it since my project already has moment and I don't need timezone support in my rrule usage.

So I installed it:

```bash
$ npm install --save --no-optional rrule
+ rrule 2.6.0
$  ls node_modules | grep luxon
# nothing
```

So far so good.  But then as soon as I bundle with webpack and run, it crashes in `./node_modules/rrule/dist/esm/src/datewithzone.js` with "`Module not found: Error: Can't resolve 'luxon'`".  Is this a limitation of webpack?  How can I use rrule without luxon?

**Comment by davidgoli** [comment]
Hi, are you able to create a sample project that reproduces this? Thanks!

**Comment by thefliik** [comment]
So the issue here appears to be that, currently, luxon is actually a required dependency (not optional). This package's main entry point, `src/index.ts`, depends on `src/rrule.ts` which depends on `src/iter/index.ts` which depends on `src/datewithzone.ts` which depends on `luxon` (all es6 static imports are required to be resolvable). The fact that this issue doesn't come up more frequently just goes to show how few people are interested in using this library without timezone support.

In order to make luxon an optional dependency, it either needs to be dynamically imported (via `import('luxon').then()`) and hidden behind a conditional, or the paths which require luxon need to be moved into a separate (and optional) package entry point.

The dynamic import route might look like this:

```ts
// src/datewithzone.ts
import dateutil from './dateutil'

try {
  import('luxon').then(luxon => DateWithZone.luxon = luxon).catch()
} catch (e) {}

export class DateWithZone {
  static luxon: { fromJSDate(date: Date): any } | undefined;

  // other stuff ...

  public rezonedDate () {
    if (this.isUTC) {
      return this.date
    }
    else if (!DateWithZone.luxon) {
      console.error(
        'Using TZID without Luxon available is unsupported. ' +
        'Returned times are in UTC, not the requested time zone'
      )

      return this.date;
    }

    const datetime = DateWithZone.luxon
      .fromJSDate(this.date)

    const rezoned = datetime.setZone(this.tzid!, { keepLocalTime: true })

    return rezoned.toJSDate()
  }
}
```

There are a few problems with this though.

1. Theoretically, this opens up the possibility of a race condition if `DateWithZone` is used before `import('luxon') has loaded.
2. I'm not sure how bundlers would treat the dynamic import. They might use code splitting to move it into a separate bundle which would then need to get loaded separately. The end user's web app would need to be able to dynamically load this code. Anyway, it makes things more complicated.

I think moving this code into a separate and optional package entry point is the right solution. This might look like:

```ts
// src/datewithzone.ts
import dateutil from './dateutil'

export class DateWithZone {
  static luxon: { fromJSDate(date: Date): any } | undefined;

  // other stuff ...

  public rezonedDate () {
    if (this.isUTC) {
      return this.date
    }
    else if (!DateWithZone.luxon) {
      console.error(
        'Using TZID without Luxon available is unsupported. ' +
        'Returned times are in UTC, not the requested time zone'
      )

      return this.date;
    }

    const datetime = DateWithZone.luxon
        .fromJSDate(this.date)

    const rezoned = datetime.setZone(this.tzid!, { keepLocalTime: true })

    return rezoned.toJSDate()
  }
}
```
and

```ts
// src/luxon/index.ts
import { DateWithZone } from '../datewithzone';
import { DateTime } from 'luxon';

DateWithZone.luxon = DateTime;
```

Usage would be like

```ts
import { RRule } from 'rrule';
import 'rrule/luxon';

// ... do stuff
```
A separate `package.json` would need to be added to `src/luxon/package.json` to allow usage of the new entry point.

**Comment by AntonSermyazhko** [comment]
Hi,
What is the progress on this issue?

**Comment by thefliik** [comment]
All the progress is contained on this page.

**Comment by KrakenTyio** [comment]
After few months i try to remove from project luxon but still see this this issue
```
Error: ./node_modules/rrule/dist/esm/src/datewithzone.js
Module not found: Error: Can't resolve 'luxon' in '/home/node/app/node_modules/rrule/dist/esm/src'
```

project is with angular 11 and we already using moment.js

**Comment by OldShaterhan** [comment]
Similar issue happened for me. In my case downgrade from `npm` 7 to `npm` 6 resolves the issue, but it isn't target solution.
