### ISSUE TITLE
jquey vulnerabilities in static analysis report.

### ISSUE THREAD

**Issue by andrius-pra** [jakubroztocil/rrule#499]
Static analysis tools marks rrule@2.6.9 as vulnerable component.

![image](https://user-images.githubusercontent.com/17968027/158984533-04f69121-cabe-4d4e-84b6-3036f94a9efc.png)

Is there any reason why demo files are included in the npm package?

**Comment by sunshineo** [comment]
I had a quick look but could not figure out whether the `tsconfig.json` or the `webpack.config.js` should be modified to exclude the demo from the package.
Maybe there should be an rrule-demo project to just host the demo

**Comment by davidgoli** [comment]
`jquery` is included in `package.json` which is probably why it's showing up here. Rrule does not import. Agree that there should be a separate project for the demo - would love to review a PR that did that.

**Comment by sunshineo** [comment]
@davidgoli I'll try

**Comment by sunshineo** [comment]
Demo page is deployed by `gh-pages` branch, it is diverged from `master` branch (for example `dist` folder not ignored and demo page served from there). It requires manual merge from `master` branch to update demo page to use the latest rrule lib.
[This PR](https://github.com/jakubroztocil/rrule/pull/509) makes `gh-pages` branch only for the demo page and use rrule from npm. Currently 2.7.0. For future updates, instead of merge from the tip of master, we simply update the version number in `package.json`

**Comment by sunshineo** [comment]
@davidgoli if we still want a completely separated project for the demo, I can do that but it will be under my Github account with url https://sunshineo.github.io/rrule/ or https://sunshineo.github.io/rrule-demo/
This will requires url changes everywhere and also better to remove the `gh-pages` in the main repo.
I'm now working on remove all demo code from `master` branch

**Comment by sunshineo** [comment]
https://github.com/jakubroztocil/rrule/pull/510
