### ISSUE TITLE
Recurrence series changes time of day in time zone after Daylight Savings

### ISSUE THREAD

**Issue by DevonStern** [jakubroztocil/rrule#550]
I have tried various configurations for the rrule as indicated in the documentation [here](https://github.com/jakubroztocil/rrule#important-use-utc-dates) and [here](https://github.com/jakubroztocil/rrule#timezone-support). It says the time of day should be the same across Daylight Savings, but that is not what I am seeing.

## Code sample

```
const rrule = new RRule({
  freq: RRule.DAILY,
  dtstart: new Date(Date.UTC(2022, 7, 18, 12, 0, 0)),
  // tzid: 'America/Denver', // output is the same whether this is included or not
})
const datetimes = rrule.between(
  new Date('2022-10-31'),
  new Date('2022-11-10')
)
```

Try out the [CodeSandbox](https://codesandbox.io/s/rrule-incorrect-times-after-daylight-savings-z0gfii). Should get similar results as long as you are in a time zone that has Daylight Savings and the `between` range includes a change in Daylight Savings.

### Expected output

The time of day in America/Denver time zone should not change after Daylight Savings (i.e. recurrence should account for Daylight Savings):

```
Mon Oct 31 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Tue Nov 01 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Wed Nov 02 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Thu Nov 03 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Fri Nov 04 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Sat Nov 05 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Sun Nov 06 2022 06:00:00 GMT-0700 (Mountain Standard Time) <-- Daylight savings change
Mon Nov 07 2022 06:00:00 GMT-0700 (Mountain Standard Time)
Tue Nov 08 2022 06:00:00 GMT-0700 (Mountain Standard Time)
Wed Nov 09 2022 06:00:00 GMT-0700 (Mountain Standard Time)
                ^^
```

### Actual output

The time of day in America/Denver time zone is changing from 6:00 to 5:00:

```
Mon Oct 31 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Tue Nov 01 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Wed Nov 02 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Thu Nov 03 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Fri Nov 04 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Sat Nov 05 2022 06:00:00 GMT-0600 (Mountain Daylight Time)
Sun Nov 06 2022 05:00:00 GMT-0700 (Mountain Standard Time) <-- Daylight savings change
Mon Nov 07 2022 05:00:00 GMT-0700 (Mountain Standard Time)
Tue Nov 08 2022 05:00:00 GMT-0700 (Mountain Standard Time)
Wed Nov 09 2022 05:00:00 GMT-0700 (Mountain Standard Time)
                ^^
```

#### Info

Version: rrule 2.7.1 (also tested with 2.4.1 and issue occurred)
OS: Windows 10 Pro, version 21H1
Browser: Chrome 104.0.5112.81 (replicated in Firefox)
Time zone: America/Denver

**Comment by kmaic** [comment]
Hi there, I am facing the same issue. Any workaround?

**Comment by dereekb** [comment]
I recall running into this issue when refactoring for the 2.7.1 update. It has the correct output when using GMT.

<img width="487" alt="Screen Shot 2022-09-19 at 12 26 57 PM" src="https://user-images.githubusercontent.com/3586580/191016886-fde51c27-ed4a-49a6-9b64-0fd9aa2067cf.png">

I don't use the built-in "tzid" field and conversions (since historically rrule hasn't particularly recommended its usage), but I was running into this myself when adding 1 day using date-util's addDay function, which took into account the mdt/mst change and gave the wrong offset. In order to properly compute the time it needed to use GMT+0/UTC, then convert afterwards.

For my project I've got a .spec file with some notes written on that since I had run into it:

https://github.com/dereekb/dbx-components/blob/2afe2bd9638f47ce87e387f0fb329c5ba9327d34/packages/date/src/lib/rrule/date.rrule.spec.ts

Without looking at any of the tzid code, my guess is the built-in timezone support may not be working in GMT then doing each conversion, which would make the time off by 1 hour after the date change.

**Comment by dereekb** [comment]
That's correct. There's not really a "bug" but confusion on how many of us interpret it as how it should work, ultimately why I suggest avoiding the usage of TZID directly.

What you're talking about with local times and not UTC times is what I was explaining above.

**Comment by michaelKaefer** [comment]
@dereekb Ok, thanks for clarification. - But I think there is no problem with using `tzid` when needed IMO.

**Comment by DevonStern** [comment]
Thank you for the clarification, @michaelKaefer! There are pieces of that in the documentation but it doesn't put it all together into a cohesive example like you did. Now I can get it to work as expected. It's a little bit weird, but I'll take weird and working over not working. :)
